/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package palindrome;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    void givenAPalindromShouldDisplayAppropriateResult() {
        assertEquals("'radar' is a palindrome", App.palindromResult("radar"));
    }

    @Test
    void givenAWordThatIsNotAPalindromShouldDisplayAppropriateResult() {
        assertEquals("'palindrome' is not a palindrome", App.palindromResult("palindrome"));
    }
}
